### ISSUE TITLE
Documentation on TMLE

### ISSUE THREAD

**Issue by nsankar** [ronikobrosly/causal-curve#30]
Sir,

Would like to know when the documentation about TMLE would be updated. Looking forward.

Thank you.

**Comment by ronikobrosly** [comment]
Hi @nsankar ! Thanks for your interest! Just bumped the version to `1.0.1`. It now includes a larger section in the documentation for TMLE: https://causal-curve.readthedocs.io/en/latest/TMLE_Regressor.html

Just wanted to remind you, if you're interested in the TMLE API, the documentation also has info: https://causal-curve.readthedocs.io/en/latest/causal_curve.html#module-causal_curve.tmle_core

**Comment by nsankar** [comment]
@ronikobrosly  Awesome. Thanks.
