### ISSUE TITLE
AttributeError: 'csr_matrix' object has no attribute 'A'

### ISSUE THREAD

**Issue by gabeschulman** [ronikobrosly/causal-curve#48]
Hey, I got the error in the title when trying to user the gps regressor class for some data I have. This came up in StackOverflow from a simple Google search https://stackoverflow.com/questions/74689845/why-did-it-happen-attributeerror-matrix-object-has-no-attribute-todense

Thanks

**Comment by ronikobrosly** [comment]
Hi @gabeschulman , do you encounter this issue when you run the GPS regressor example in the documentation or no?

**Comment by gabeschulman** [comment]
Hi @ronikobrosly - I realized this was a dependency issue (I had a later version of scipy installed in my python environment than the version that this package needs). Sorry about that!

**Comment by ronikobrosly** [comment]
No worries @gabeschulman . I really should update and pin the dependencies. Just need to find the time.
